version: 2.1
jobs:
  deploy:
    machine:
      enabled: true
    steps:
      - add_ssh_keys:
          fingerprints:
            - "36:f0:a0:c7:85:49:d6:54:bc:2e:9c:f8:c2:cd:03:da" #SSHするサーバの秘密鍵を登録後、ハッシュ化されているfingerprintsをコピペする。
      - run: ssh -p $SSH_PORT $SSH_USER@$SSH_HOST "/var/www/rails/goshichigo/deploy.sh"

workflows:
  version: 2.1
  deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: master
