~/p/v/g/d/gurumyu ❯❯❯ git diff config/database.yml
diff --git a/config/database.yml b/config/database.yml
index 1c1a37c..7e3ad2d 100644
--- a/config/database.yml
+++ b/config/database.yml
@@ -1,25 +1,35 @@
-# SQLite version 3.x
-#   gem install sqlite3
+# MySQL. Versions 5.1.10 and up are supported.
#
-#   Ensure the SQLite 3 gem is defined in your Gemfile
-#   gem 'sqlite3'
+# Install the MySQL driver
+#   gem install mysql2
+#
+# Ensure the MySQL gem is defined in your Gemfile
+#   gem 'mysql2'
+#
+# And be sure to use new-style password hashing:
+#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
-  adapter: sqlite3
-  pool: 5
-  timeout: 5000
+  adapter: mysql2
+  encoding: utf8
+  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
+  username: root
+  password:
+  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
-  database: db/development.sqlite3
+  database: [データベース名]_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
-  database: db/test.sqlite3
+  database: [データベース名]_test

production:
  <<: *default
-  database: db/production.sqlite3
+  database: [データベース名]
+  username: [ユーザー名]
+  password: <%= ENV['GAMBARASE_DATABASE_PASSWORD'] %>
